### ISSUE TITLE
Class 'EfgFormLookupSelectMenu' not found

### ISSUE THREAD

**Issue by haendersonfox** [pbd-kn/contao-efg-bundle#1]
nachfolgend die fehlermeldung, beim versuch, die erweiterung zu installieren:

10:26:49 CRITICAL  [console] Error thrown while running command "cache:warmup --env=prod". Message: "Class 'EfgFormLookupSelectMenu' not found" ["exception" => Error { …},"command" => "cache:warmup --env=prod","message" => "Class 'EfgFormLookupSelectMenu' not found"]
59
60
In FormDependentMandatoryField.php line 302:
61
                                                                               
62
  Attempted to load class "EfgFormLookupSelectMenu" from the global namespace  
63
  .                                                                            
64
  Did you forget a "use" statement for "PBDKN\Efgco4\Resources\contao\forms\E  
65
  fgFormLookupSelectMenu"?                                                     
66
                                                                               
67
68
cache:warmup [--no-optional-warmers] [-h|--help] [-q|--quiet] [-v|vv|vvv|--verbose] [-V|--version] [--ansi] [--no-ansi] [-n|--no-interaction] [-e|--env ENV] [--] <command>
69
70
Script Contao\ManagerBundle\Composer\ScriptHandler::initializeApplication handling the post-update-cmd event terminated with an exception
71
72
In ScriptHandler.php line 89:
73
                                                                               
74
  An error occurred while executing the "cache:warmup" command: 10:26:49 CRIT  
75
  ICAL  [console] Error thrown while running command "cache:warmup --env=prod  
76
  ". Message: "Class 'EfgFormLookupSelectMenu' not found" ["exception" => Err  
77
  or { …},"command" => "cache:warmup --env=prod","message" => "Class 'EfgForm  
78
  LookupSelectMenu' not found"]                                                
79
                                                                               
80
  In FormDependentMandatoryField.php line 302:                                 
81
                                                                               
82
                                                                               
83
    Attempted to load class "EfgFormLookupSelectMenu" from the global namespa  
84
  ce                                                                           
85
    .                                                                          
86
                                                                               
87
    Did you forget a "use" statement for "PBDKN\Efgco4\Resources\contao\forms  
88
  \E                                                                           
89
    fgFormLookupSelectMenu"?                                                   
90
                                                                               
91
                                                                               
92
                                                                               
93
                                                                               
94
  cache:warmup [--no-optional-warmers] [-h|--help] [-q|--quiet] [-v|vv|vvv|--  
95
  verbose] [-V|--version] [--ansi] [--no-ansi] [-n|--no-interaction] [-e|--en  
96
  v ENV] [--] <command>                                                        
97
                                                                               
98
99
update [--with WITH] [--prefer-source] [--prefer-dist] [--dry-run] [--dev] [--no-dev] [--lock] [--no-install] [--no-autoloader] [--no-scripts] [--no-suggest] [--no-progress] [-w|--with-dependencies] [-W|--with-all-dependencies] [-v|vv|vvv|--verbose] [-o|--optimize-autoloader] [-a|--classmap-authoritative] [--apcu-autoloader] [--apcu-autoloader-prefix APCU-AUTOLOADER-PREFIX] [--ignore-platform-req IGNORE-PLATFORM-REQ] [--ignore-platform-reqs] [--prefer-stable] [--prefer-lowest] [-i|--interactive] [--root-reqs] [--] [<packages>...]
100
101
102
# Process terminated with exit code 1
103
# Result: General error

**Comment by pbd-kn** [comment]
Hmm,
ich werde mich mal drum kümmern. Bei anderen, einschließlich bei mir hat es geklappt.
Kann aber ein paar Tage dauern, da ich es nebenher betreibe.
LG
Peter

**Comment by pbd-kn** [comment]
Hmm,

ich werde mich mal drum kümmern. Bei anderen, einschließlich bei mir hat es geklappt.

Kann aber ein paar Tage dauern, da ich es nebenher betreibe.

LG

Peter

 

 

Von: haendersonfox 
Gesendet: Montag, 12. April 2021 10:47
An: pbd-kn/contao-efg-bundle ***@***.***>
Cc: Subscribed ***@***.***>
Betreff: [pbd-kn/contao-efg-bundle] Class 'EfgFormLookupSelectMenu' not found (#1)

 

nachfolgend die fehlermeldung, beim versuch, die erweiterung zu installieren:

10:26:49 CRITICAL [console] Error thrown while running command "cache:warmup --env=prod". Message: "Class 'EfgFormLookupSelectMenu' not found" ["exception" => Error { …},"command" => "cache:warmup --env=prod","message" => "Class 'EfgFormLookupSelectMenu' not found"]
59
60
In FormDependentMandatoryField.php line 302:
61

62
Attempted to load class "EfgFormLookupSelectMenu" from the global namespace
63
.
64
Did you forget a "use" statement for "PBDKN\Efgco4\Resources\contao\forms\E
65
fgFormLookupSelectMenu"?
66

67
68
cache:warmup [--no-optional-warmers] [-h|--help] [-q|--quiet] [-v|vv|vvv|--verbose] [-V|--version] [--ansi] [--no-ansi] [-n|--no-interaction] [-e|--env ENV] [--] 
69
70
Script Contao\ManagerBundle\Composer\ScriptHandler::initializeApplication handling the post-update-cmd event terminated with an exception
71
72
In ScriptHandler.php line 89:
73

74
An error occurred while executing the "cache:warmup" command: 10:26:49 CRIT
75
ICAL [console] Error thrown while running command "cache:warmup --env=prod
76
". Message: "Class 'EfgFormLookupSelectMenu' not found" ["exception" => Err
77
or { …},"command" => "cache:warmup --env=prod","message" => "Class 'EfgForm
78
LookupSelectMenu' not found"]
79

80
In FormDependentMandatoryField.php line 302:
81

82

83
Attempted to load class "EfgFormLookupSelectMenu" from the global namespa
84
ce
85
.
86

87
Did you forget a "use" statement for "PBDKN\Efgco4\Resources\contao\forms
88
\E
89
fgFormLookupSelectMenu"?
90

91

92

93

94
cache:warmup [--no-optional-warmers] [-h|--help] [-q|--quiet] [-v|vv|vvv|--
95
verbose] [-V|--version] [--ansi] [--no-ansi] [-n|--no-interaction] [-e|--en
96
v ENV] [--] 
97

98
99
update [--with WITH] [--prefer-source] [--prefer-dist] [--dry-run] [--dev] [--no-dev] [--lock] [--no-install] [--no-autoloader] [--no-scripts] [--no-suggest] [--no-progress] [-w|--with-dependencies] [-W|--with-all-dependencies] [-v|vv|vvv|--verbose] [-o|--optimize-autoloader] [-a|--classmap-authoritative] [--apcu-autoloader] [--apcu-autoloader-prefix APCU-AUTOLOADER-PREFIX] [--ignore-platform-req IGNORE-PLATFORM-REQ] [--ignore-platform-reqs] [--prefer-stable] [--prefer-lowest] [-i|--interactive] [--root-reqs] [--] [...]
100
101
102


Process terminated with exit code 1


103


Result: General error

**Comment by pbd-kn** [comment]
Hi,

ich habe einige Änderungen gemacht.

Bitte versuch es mit 1.0.4-RC2

Aber Achtung nach dem Upgrade müssen die entsprechenden Formulare aktualisiert werden

BE->Formulare  formular auswählen bearbeiten und dann speichern (evtl. mit mehrere bearbeiten)

LG

Peter

 

 

Von: haendersonfox ***@***.***> 
Gesendet: Montag, 12. April 2021 10:47
An: pbd-kn/contao-efg-bundle ***@***.***>
Cc: Subscribed ***@***.***>
Betreff: [pbd-kn/contao-efg-bundle] Class 'EfgFormLookupSelectMenu' not found (#1)

 

nachfolgend die fehlermeldung, beim versuch, die erweiterung zu installieren:

10:26:49 CRITICAL [console] Error thrown while running command "cache:warmup --env=prod". Message: "Class 'EfgFormLookupSelectMenu' not found" ["exception" => Error { …},"command" => "cache:warmup --env=prod","message" => "Class 'EfgFormLookupSelectMenu' not found"]
59
60
In FormDependentMandatoryField.php line 302:
61

62
Attempted to load class "EfgFormLookupSelectMenu" from the global namespace
63
.
64
Did you forget a "use" statement for "PBDKN\Efgco4\Resources\contao\forms\E
65
fgFormLookupSelectMenu"?
66

67
68
cache:warmup [--no-optional-warmers] [-h|--help] [-q|--quiet] [-v|vv|vvv|--verbose] [-V|--version] [--ansi] [--no-ansi] [-n|--no-interaction] [-e|--env ENV] [--] 
69
70
Script Contao\ManagerBundle\Composer\ScriptHandler::initializeApplication handling the post-update-cmd event terminated with an exception
71
72
In ScriptHandler.php line 89:
73

74
An error occurred while executing the "cache:warmup" command: 10:26:49 CRIT
75
ICAL [console] Error thrown while running command "cache:warmup --env=prod
76
". Message: "Class 'EfgFormLookupSelectMenu' not found" ["exception" => Err
77
or { …},"command" => "cache:warmup --env=prod","message" => "Class 'EfgForm
78
LookupSelectMenu' not found"]
79

80
In FormDependentMandatoryField.php line 302:
81

82

83
Attempted to load class "EfgFormLookupSelectMenu" from the global namespa
84
ce
85
.
86

87
Did you forget a "use" statement for "PBDKN\Efgco4\Resources\contao\forms
88
\E
89
fgFormLookupSelectMenu"?
90

91

92

93

94
cache:warmup [--no-optional-warmers] [-h|--help] [-q|--quiet] [-v|vv|vvv|--
95
verbose] [-V|--version] [--ansi] [--no-ansi] [-n|--no-interaction] [-e|--en
96
v ENV] [--] 
97

98
99
update [--with WITH] [--prefer-source] [--prefer-dist] [--dry-run] [--dev] [--no-dev] [--lock] [--no-install] [--no-autoloader] [--no-scripts] [--no-suggest] [--no-progress] [-w|--with-dependencies] [-W|--with-all-dependencies] [-v|vv|vvv|--verbose] [-o|--optimize-autoloader] [-a|--classmap-authoritative] [--apcu-autoloader] [--apcu-autoloader-prefix APCU-AUTOLOADER-PREFIX] [--ignore-platform-req IGNORE-PLATFORM-REQ] [--ignore-platform-reqs] [--prefer-stable] [--prefer-lowest] [-i|--interactive] [--root-reqs] [--] [...]
100
101
102


Process terminated with exit code 1


103


Result: General error

**Comment by pbd-kn** [comment]
erledigt
