### ISSUE TITLE
Portierung zu Contao 4.4

### ISSUE THREAD

**Issue by ff1601com** [pbd-kn/contao-efg-bundle#10]
Hallo nochmal @pbd-kn,

ich habe mir das Bundle nun geforkt und etwas getestet.
Ich habe dabei die composer.json folgendermaßen angepasst:
```php
"require": {
        "php": "^7.2 || ^8.0",
        "contao/core-bundle": "^4.4",
        "codefog/contao-haste": "^4.24",
        "symfony/config": "^4.4 || ^5.1",
        "symfony/dependency-injection": "^4.4 || ^5.1",
        "symfony/http-kernel": "^4.4 || ^5.1"
    },
```

Dabei erzeugten folgende Zeilen Fehler bei der Installation:
```php
        "symfony/config": "^4.4 || ^5.1",
        "symfony/dependency-injection": "^4.4 || ^5.1",
        "symfony/http-kernel": "^4.4 || ^5.1"
```

> Problem 1
>     - Root composer.json requires pbd-kn/contao-efg-bundle @dev -> satisfiable by pbd-kn/contao-efg-bundle[dev-deployment/dev].
>     - pbd-kn/contao-efg-bundle dev-deployment/dev requires symfony/config ^4.4 || ^5.1 -> found symfony/config[v4.4.0-BETA1, v4.4.0-BETA2, v4.4.0-RC1, v4.4.0, v4.4.1, v4.4.2, v4.4.3, v4.4.4, v4.4.5, v4.4.6, v4.4.7, v4.4.8, v4.4.9, v4.4.10, v4.4.11, v4.4.12, v4.4.13, v4.4.14, v4.4.15, v4.4.16, v4.4.17, v4.4.18, v4.4.19, v4.4.20, v4.4.22, v4.4.23, v4.4.25, v4.4.26, v4.4.27, v4.4.30, 4.4.x-dev, v5.1.0-BETA1, v5.1.0-RC1, v5.1.0-RC2, v5.1.0, v5.1.1, v5.1.2, v5.1.3, v5.1.4, v5.1.5, v5.1.6, v5.1.7, v5.1.8, v5.1.9, v5.1.10, v5.1.11, 5.1.x-dev, v5.2.0-BETA1, v5.2.0-BETA2, v5.2.0-BETA3, v5.2.0-RC1, v5.2.0-RC2, v5.2.0, v5.2.1, v5.2.2, v5.2.3, v5.2.4, v5.2.7, v5.2.8, v5.2.10, v5.2.11, v5.2.12, 5.2.x-dev, v5.3.0-BETA1, v5.3.0-BETA2, v5.3.0-BETA3, v5.3.0-RC1, v5.3.0, v5.3.2, v5.3.3, v5.3.4, 5.3.x-dev, 5.4.x-dev] but these were not loaded, likely because it conflicts with another require.

##

Ich habe die entsprechenden Bundles dann testweise über "*" laden lassen, wodurch die Installation weiterging.
```php
        "symfony/config": "*",
        "symfony/dependency-injection": "*",
        "symfony/http-kernel": "*"
```

Danach lief er noch in das Problem, dass die Klassen (class_alias) in der autoload.php nicht gefunden wurden:

> Warning: Class 'PBDKN\Efgco4\Resources\contao\drivers\DC_Formdata' not found in /dev-system/src/pbd-kn/contao-efg-bundle/src/Resources/contao/config/autoload.php on line 31
> 10:26:21 ERROR     [console] Error thrown while running command "--ansi cache:warmup -v --env=prod". Message: "Class 'Backend' not found" ["exception" => Error { …},"command" => "--ansi cache:warmup -v --env=prod","message" => "Class 'Backend' not found"]

Nachdem ich die Klassen-Aliase auskommentiert hatte, funktionierte die Installation problemlos.

```php
class_alias(PBDKN\Efgco4\Resources\contao\drivers\DC_Formdata::class, 'DC_Formdata');
class_alias(PBDKN\Efgco4\Resources\contao\classes\Formdata::class, 'Formdata');
class_alias(PBDKN\Efgco4\Resources\contao\classes\FormdataBackend::class, 'FormdataBackend');
```

Ich könnte mir vorstellen, dass es nach Behebung der Fehler in der composer.json und der autoload.php ohne weitere Anpassungen funktioniert.

Hast du hier eine Idee für einen Fix in Contao 4.4?

**Comment by pbd-kn** [comment]
Hi,
Danke zuerst mal für die Mühe
Vor Ende September komme ich aber nicht dazu mich drum zu kümmern.
Wenn Deine Änderungen funktionieren, probiere ich sie danach gerne auch unter 4.9 aus und übernehme sie gegebenenfalls

**Comment by ff1601com** [comment]
Hi @pbd-kn,
kein Problem. Es eilt ja nicht.

Bisher funktioniert es so noch nicht, da die Class_Aliase nicht mehr geladen werden.
Ich probiere hier etwas herum und sehe zu, ob ich das behoben bekomme.

Dann würde ich dir einen Pull-Request aufmachen.
Mir sind noch ein paar mehr Dinge aufgefallen, die bereits im ursprünglichen EFG nicht richtig funktionierten (z.B Auswertung von loadFormField-Hooks). Das würde ich mir gleich mit ansehen.

**Comment by pbd-kn** [comment]
Hi, bist Du erfolgreich geworden,
ich möchte gerne die Anfrage schließen

**Comment by pbd-kn** [comment]
Keine Antwort mehr bekommen
