### ISSUE TITLE
"(EFG) Bestätigung per E-Mail versenden" versendet keine E-Mail

### ISSUE THREAD

**Issue by klauswagner** [pbd-kn/contao-efg-bundle#15]
Hallo,
leider musste ich feststellen, dass die Funktion "**(EFG) Bestätigung per E-Mail versenden**" keine E-Mail versendet.
In "_Formularfeld mit E-Mail-Adresse des Empfängers_" ist das Feld "email" aus dem Formular definiert. Als Text habe ich einen einfachen Text ohne Inserttags eingetragen. Es werden keine Dateien angehängt und keine HTML-Vorlage verwendet.

Die Standard-Funktion "Formulardaten versenden" funktioniert hingegen ohne Probleme. Egal ob in der parameters.yml ein SMTP-Account hinterlegt ist oder nicht.

Im System-Log wird kein Error eingetragen und der Debug-Modus hilft mir bei der Fehlersuche leider auch nicht weiter.

-----

_(Contao 4.9.23 / PHP 7.4 / contao-efg-bundle Release 1.0.18)_

**Comment by pbd-kn** [comment]
Hi,
das hatte ich eigentlich ausführlich getestet.
Ich mach mich nochmals dran, kann aber ein paar Tage dauern.
LG

**Comment by pbd-kn** [comment]
Unter 1.0.21 getestet.
Fehlerbehebung durchgeführt.
Bei weiteren Fehler bitte erneut melden

**Comment by pbd-kn** [comment]
closed
