### ISSUE TITLE
Export as Excel / CSV dont work

### ISSUE THREAD

**Issue by LBeckX** [pbd-kn/contao-efg-bundle#18]
Man bekommt leider einen 500 in Contao 4.13

**Comment by pbd-kn** [comment]
Hmm, ich kann den Fehler nicht nachfolziehen. Kannst Du mir ein paar nähere Infos geben

**Comment by LBeckX** [comment]
okay, strange.
Im Einsatz waren:

- Neue Contao 4.13 Installation
- PHP: 7.4
- MySQL 5.7

Leider habe ich keinen Zugriff auf die error-logs bekommen da es nicht mein Server war.

**Comment by pbd-kn** [comment]
Und Fehler reproduzieren, wie??

**Comment by LBeckX** [comment]
1. Formular-Daten in der Datenbank speichern
2. Gespeicherte Formulardaten als .xlsx oder .csv exportieren

**Comment by pbd-kn** [comment]
Wie schon gesagt funktioniert bei mir einwandfrei. Sind in dem Formular schon Daten enthalten

**Comment by LBeckX** [comment]
Okay, strange. Wie schon gesagt, habe und hatte ich leider keinen Zugriff auf die Error-Logs. Daher kann das Ticket einfach als nicht relevant betrachtet werden. Sollte sich noch einmal was ändern oder mir der Fehler auffallen, erstelle ich ein neues mit Error-Log.

**Comment by pbd-kn** [comment]
ok

**Comment by kampfq** [comment]
Habe den selben Fehler:

Attempted to load class "xlsexport" from the global namespace.
Did you forget a "use" statement?
