### ISSUE TITLE
Portierung nur zu Contao 4.9?

### ISSUE THREAD

**Issue by ff1601com** [pbd-kn/contao-efg-bundle#9]
Hallo @pbd-kn,

ich habe gerade gemerkt, dass das Bundle nur ab Version 4.9 installiert werden kann.
Gibt es dafür einen bestimmten Grund? Wurde hier etwas verwendet, was mit Contao 4.4 inkompatibel ist?

Beim Lesen der Erweiterung kam mir `Portierung EFG nach Contao 4` entgegen und ich dachte mir, das umfasst dann alle Contao 4 Versionen und nicht nur die ab 4.9.

Habe auch kurz mal in den src geschaut und nichts gesehen, was nur mit Contao 4.9 funktionieren würde.
Kann aber natürlich sein, dass ich hier etwas übersehen habe. War nur ein flüchtiger Blick.

Durch das Require in der composer.json ist es aber festgesetzt.
> contao/core-bundle: ^4.9

##

Noch eine zweite Frage:
Wenn ich nun bereits efg über den legacy weg (system/modules/) installiert habe, wie würde ich Dein Bundle dann installieren?
Einfach zusätzlich installieren und danach die Formulare neu speichern?
Das alte efg-bundle deinstallieren?

**Comment by pbd-kn** [comment]
Hi,

Danke für die Rückmeldung,
Nee es spricht eigentlich nichts dagegen. Ich habe es alt mit der contao 4.9 entwickelt, Du kannst es gerne mit 4.4 testen. Gib mir bitte Rückmeldung, dann übernehme ich es.

Zur Übernahme
Ja, ich habe es bei mit so gemacht.
System/modules/efg gelöscht

Mit Contao Manager installiert,
Die Formulare neu gespeichert.

Schon hats geflutscht. Hoffentlich bei Dir auch.
LG
Peter
